before:
  hooks:
    - go mod download

builds:
  # Build main plugin
  - id: plugin
    binary: cq-source-sharepoint
    flags:
      - -buildmode=exe
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X github.com/koltyakov/cq-source-sharepoint/plugin.Version={{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  # Build spctl (CLI)
  - id: spctl
    main: ./cmd/spctl/
    binary: spctl
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: plugin
    builds: [plugin]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: zip
  - id: spctl
    builds: [spctl]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
